version: "3.5"

services:
  polyeventbackend:
    image: polyeventbackend:latest
    container_name: polyeventbackend
    ports:
      - 8080:8080
    depends_on:
      - hyperplanning

  hyperplanning:
      image: hyperplanning:latest
      build: ./dotnet
      container_name: hyperplanning
      ports:
        - 9090:9090

