package fr.unice.polytech.isa.polyevent.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-03-23T09:47:39.225+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", name = "DemanderEvenement")
@XmlSeeAlso({ObjectFactory.class})
public interface DemanderEvenement {

    @WebMethod
    @RequestWrapper(localName = "demanderCreationEvenement", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", className = "fr.unice.polytech.isa.polyevent.stubs.DemanderCreationEvenement")
    @ResponseWrapper(localName = "demanderCreationEvenementResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", className = "fr.unice.polytech.isa.polyevent.stubs.DemanderCreationEvenementResponse")
    public void demanderCreationEvenement(
        @WebParam(name = "organisateur", targetNamespace = "")
        fr.unice.polytech.isa.polyevent.stubs.Organisateur organisateur,
        @WebParam(name = "nom", targetNamespace = "")
        java.lang.String nom,
        @WebParam(name = "date_debut", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dateDebut,
        @WebParam(name = "date_fin", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dateFin,
        @WebParam(name = "demande_reservations", targetNamespace = "")
        java.util.List<fr.unice.polytech.isa.polyevent.stubs.DemandeReservationSalle> demandeReservations
    );
}
