
package fr.unice.polytech.isa.polyevent.stubs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemanderEvenement", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemanderEvenement {


    /**
     * 
     * @param dateDebut
     * @param organisateur
     * @param dateFin
     * @param nom
     * @param demandeReservations
     */
    @WebMethod
    @RequestWrapper(localName = "demanderCreationEvenement", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", className = "fr.unice.polytech.isa.polyevent.stubs.DemanderCreationEvenement")
    @ResponseWrapper(localName = "demanderCreationEvenementResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", className = "fr.unice.polytech.isa.polyevent.stubs.DemanderCreationEvenementResponse")
    public void demanderCreationEvenement(
        @WebParam(name = "organisateur", targetNamespace = "")
        Organisateur organisateur,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "date_debut", targetNamespace = "")
        XMLGregorianCalendar dateDebut,
        @WebParam(name = "date_fin", targetNamespace = "")
        XMLGregorianCalendar dateFin,
        @WebParam(name = "demande_reservations", targetNamespace = "")
        List<DemandeReservationSalle> demandeReservations);

}
