package fr.unice.polytech.isa.polyevent.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-03-23T09:47:39.264+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "DemandeEvenementService", 
                  wsdlLocation = "file:/Users/florian/Desktop/isa_dev_ops/main/polyeventclients/organisateur/src/main/resources/DemandeEvenementWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement") 
public class DemandeEvenementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", "DemandeEvenementService");
    public final static QName DemandeEvenementPort = new QName("http://www.polytech.unice.fr/si/4a/isa/polyevent/demandeEvenement", "DemandeEvenementPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/florian/Desktop/isa_dev_ops/main/polyeventclients/organisateur/src/main/resources/DemandeEvenementWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemandeEvenementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/florian/Desktop/isa_dev_ops/main/polyeventclients/organisateur/src/main/resources/DemandeEvenementWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemandeEvenementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemandeEvenementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemandeEvenementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DemandeEvenementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemandeEvenementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemandeEvenementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DemanderEvenement
     */
    @WebEndpoint(name = "DemandeEvenementPort")
    public DemanderEvenement getDemandeEvenementPort() {
        return super.getPort(DemandeEvenementPort, DemanderEvenement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemanderEvenement
     */
    @WebEndpoint(name = "DemandeEvenementPort")
    public DemanderEvenement getDemandeEvenementPort(WebServiceFeature... features) {
        return super.getPort(DemandeEvenementPort, DemanderEvenement.class, features);
    }

}
